// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Send a message to the AI agent
Future<String> agentSendMessage({required String msg}) =>
    RustLib.instance.api.crateApiAgentAgentSendMessage(msg: msg);

/// Approve or reject a tool call
Future<void> agentApproveTool({required bool approve, String? reason}) =>
    RustLib.instance.api
        .crateApiAgentAgentApproveTool(approve: approve, reason: reason);

/// Reset the agent session
Future<void> agentResetSession() =>
    RustLib.instance.api.crateApiAgentAgentResetSession();

/// Cancel the current agent operation
Future<void> agentCancel() => RustLib.instance.api.crateApiAgentAgentCancel();

/// Get agent status
Future<String> agentStatus() => RustLib.instance.api.crateApiAgentAgentStatus();

/// Get agent history list
Future<List<String>> agentGetHistory() =>
    RustLib.instance.api.crateApiAgentAgentGetHistory();

/// Load a specific agent session
Future<String> loadAgentSession({required String sessionId}) =>
    RustLib.instance.api.crateApiAgentLoadAgentSession(sessionId: sessionId);

/// Save an agent session
Future<void> saveAgentSession(
        {required String sessionId, required String data}) =>
    RustLib.instance.api
        .crateApiAgentSaveAgentSession(sessionId: sessionId, data: data);

/// Delete an agent session
Future<void> agentDeleteSession({required String sessionId}) =>
    RustLib.instance.api.crateApiAgentAgentDeleteSession(sessionId: sessionId);

/// Get custom AI config
Future<String> getCustomAiConfig() =>
    RustLib.instance.api.crateApiAgentGetCustomAiConfig();

/// Save custom AI config
Future<void> saveCustomAiConfig({required String config}) =>
    RustLib.instance.api.crateApiAgentSaveCustomAiConfig(config: config);

/// Switch active project for the agent
Future<void> switchAgentProject({required String projectId}) =>
    RustLib.instance.api.crateApiAgentSwitchAgentProject(projectId: projectId);

/// Load history page
Future<List<String>> loadHistoryPage(
        {required int page, required int pageSize}) =>
    RustLib.instance.api
        .crateApiAgentLoadHistoryPage(page: page, pageSize: pageSize);
