// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_data_dir`

/// Get Cloudflare tunnel configuration
Future<String> loadCloudflareConfig() =>
    RustLib.instance.api.crateApiCloudflareLoadCloudflareConfig();

/// Save Cloudflare tunnel configuration
Future<void> saveCloudflareConfig({required String yaml}) =>
    RustLib.instance.api.crateApiCloudflareSaveCloudflareConfig(yaml: yaml);
