// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// List supported programming languages for code RAG
Future<List<String>> codeRagSupportedLanguages() =>
    RustLib.instance.api.crateApiCodeRagCodeRagSupportedLanguages();

/// Get file extension to language mapping
Future<Map<String, String>> codeRagExtensionMap() =>
    RustLib.instance.api.crateApiCodeRagCodeRagExtensionMap();

/// Check code RAG system health
Future<String> codeRagHealth() =>
    RustLib.instance.api.crateApiCodeRagCodeRagHealth();
