// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `collect_entries`

/// List files in a directory (non-recursive)
Future<List<FileEntry>> listDirectory({required String path}) =>
    RustLib.instance.api.crateApiFilesListDirectory(path: path);

/// Read file content as string
Future<String> readFileContent({required String path}) =>
    RustLib.instance.api.crateApiFilesReadFileContent(path: path);

/// Write content to file
Future<void> writeFileContent(
        {required String path, required String content}) =>
    RustLib.instance.api
        .crateApiFilesWriteFileContent(path: path, content: content);

/// Create a new file
Future<void> createFile({required String path}) =>
    RustLib.instance.api.crateApiFilesCreateFile(path: path);

/// Create a new folder
Future<void> createFolder({required String path}) =>
    RustLib.instance.api.crateApiFilesCreateFolder(path: path);

/// Get directory contents (recursive)
Future<List<FileEntry>> getDirectoryContents({required String path}) =>
    RustLib.instance.api.crateApiFilesGetDirectoryContents(path: path);

class FileEntry {
  final String name;
  final String path;
  final bool isFolder;

  const FileEntry({
    required this.name,
    required this.path,
    required this.isFolder,
  });

  @override
  int get hashCode => name.hashCode ^ path.hashCode ^ isFolder.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FileEntry &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          path == other.path &&
          isFolder == other.isFolder;
}
