// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get git status for a working directory
Future<String> gitGetStatus({required String cwd}) =>
    RustLib.instance.api.crateApiGitGitGetStatus(cwd: cwd);

/// Stage a file
Future<void> gitStageFile({required String cwd, required String file}) =>
    RustLib.instance.api.crateApiGitGitStageFile(cwd: cwd, file: file);

/// Stage all files
Future<void> gitStageAll({required String cwd}) =>
    RustLib.instance.api.crateApiGitGitStageAll(cwd: cwd);

/// Commit with a message
Future<void> gitCommit({required String cwd, required String message}) =>
    RustLib.instance.api.crateApiGitGitCommit(cwd: cwd, message: message);

/// Push commits
Future<void> gitPush({required String cwd}) =>
    RustLib.instance.api.crateApiGitGitPush(cwd: cwd);

/// Pull changes
Future<void> gitPull({required String cwd}) =>
    RustLib.instance.api.crateApiGitGitPull(cwd: cwd);

/// Get git log
Future<List<GitCommit>> gitGetLog({required String cwd, int? limit}) =>
    RustLib.instance.api.crateApiGitGitGetLog(cwd: cwd, limit: limit);

class GitCommit {
  final String hash;
  final String author;
  final String email;
  final PlatformInt64 timestamp;
  final String message;

  const GitCommit({
    required this.hash,
    required this.author,
    required this.email,
    required this.timestamp,
    required this.message,
  });

  @override
  int get hashCode =>
      hash.hashCode ^
      author.hashCode ^
      email.hashCode ^
      timestamp.hashCode ^
      message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCommit &&
          runtimeType == other.runtimeType &&
          hash == other.hash &&
          author == other.author &&
          email == other.email &&
          timestamp == other.timestamp &&
          message == other.message;
}
