// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get available language runtimes
Future<List<RuntimeInfo>> getLanguageRuntimes() =>
    RustLib.instance.api.crateApiLanguageGetLanguageRuntimes();

class RuntimeInfo {
  final String name;
  final String version;

  const RuntimeInfo({
    required this.name,
    required this.version,
  });

  @override
  int get hashCode => name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RuntimeInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version;
}
