// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Send an HTTP request (Mini Postman)
Future<HttpResponse> sendHttpRequest(
        {required String method,
        required String url,
        List<HeaderPair>? headers,
        String? body}) =>
    RustLib.instance.api.crateApiNetworkSendHttpRequest(
        method: method, url: url, headers: headers, body: body);

/// DNS lookup
Future<List<String>> dnsLookup({required String host}) =>
    RustLib.instance.api.crateApiNetworkDnsLookup(host: host);

/// Ping a host
Future<PingResult> pingHost({required String host}) =>
    RustLib.instance.api.crateApiNetworkPingHost(host: host);

/// SSL certificate info
Future<String> sslCertificateInfo({required String url}) =>
    RustLib.instance.api.crateApiNetworkSslCertificateInfo(url: url);

/// Check if a port is in use
Future<bool> checkPortStatus({required int port}) =>
    RustLib.instance.api.crateApiNetworkCheckPortStatus(port: port);

class HeaderPair {
  final String name;
  final String value;

  const HeaderPair({
    required this.name,
    required this.value,
  });

  @override
  int get hashCode => name.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HeaderPair &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          value == other.value;
}

class HttpResponse {
  final int status;
  final List<HeaderPair> headers;
  final String body;

  const HttpResponse({
    required this.status,
    required this.headers,
    required this.body,
  });

  @override
  int get hashCode => status.hashCode ^ headers.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HttpResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          headers == other.headers &&
          body == other.body;
}

class PingResult {
  final bool reachable;
  final PlatformInt64 latencyMs;

  const PingResult({
    required this.reachable,
    required this.latencyMs,
  });

  @override
  int get hashCode => reachable.hashCode ^ latencyMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PingResult &&
          runtimeType == other.runtimeType &&
          reachable == other.reachable &&
          latencyMs == other.latencyMs;
}
