// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_data_dir`, `logs_dir`, `projects_config_path`

/// Greeting function to verify FRB connection.
Future<String> greet({required String name}) =>
    RustLib.instance.api.crateApiProcessGreet(name: name);

/// Start a project process
Future<void> startProjectProcess({required String projectId}) =>
    RustLib.instance.api
        .crateApiProcessStartProjectProcess(projectId: projectId);

/// Stop a project process
Future<void> stopProjectProcess({required String projectId}) =>
    RustLib.instance.api
        .crateApiProcessStopProjectProcess(projectId: projectId);

/// Get all registered projects
Future<List<ProjectInfo>> getProjects() =>
    RustLib.instance.api.crateApiProcessGetProjects();

/// Register a new project
Future<String> registerProject(
        {required String name,
        required String command,
        required List<String> args,
        String? cwd,
        required bool autoRestart,
        int? port}) =>
    RustLib.instance.api.crateApiProcessRegisterProject(
        name: name,
        command: command,
        args: args,
        cwd: cwd,
        autoRestart: autoRestart,
        port: port);

/// Delete a project
Future<void> deregisterProject({required String projectId}) =>
    RustLib.instance.api.crateApiProcessDeregisterProject(projectId: projectId);

/// Get project process logs
Future<List<LogLine>> getProjectLogs({required String projectId}) =>
    RustLib.instance.api.crateApiProcessGetProjectLogs(projectId: projectId);

/// Force kill a process
Future<void> forceKillProcess({required int pid}) =>
    RustLib.instance.api.crateApiProcessForceKillProcess(pid: pid);

class LogLine {
  final String text;
  final String stream;
  final PlatformInt64 timestamp;

  const LogLine({
    required this.text,
    required this.stream,
    required this.timestamp,
  });

  @override
  int get hashCode => text.hashCode ^ stream.hashCode ^ timestamp.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LogLine &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          stream == other.stream &&
          timestamp == other.timestamp;
}

class ProjectInfo {
  final String id;
  final String name;
  final String command;
  final List<String> args;
  final String? cwd;
  final bool autoRestart;
  final int? port;

  const ProjectInfo({
    required this.id,
    required this.name,
    required this.command,
    required this.args,
    this.cwd,
    required this.autoRestart,
    this.port,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      command.hashCode ^
      args.hashCode ^
      cwd.hashCode ^
      autoRestart.hashCode ^
      port.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          command == other.command &&
          args == other.args &&
          cwd == other.cwd &&
          autoRestart == other.autoRestart &&
          port == other.port;
}
