// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `app_data_dir`

/// Get application settings
Future<String> getSettings() =>
    RustLib.instance.api.crateApiSettingsGetSettings();

/// Save application settings
Future<void> saveSettings({required String content}) =>
    RustLib.instance.api.crateApiSettingsSaveSettings(content: content);

/// Reset settings to default
Future<void> resetSettings() =>
    RustLib.instance.api.crateApiSettingsResetSettings();
