// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get table list from SQLite database
Future<List<String>> getSqliteTables({required String dbPath}) =>
    RustLib.instance.api.crateApiSqliteGetSqliteTables(dbPath: dbPath);

/// Get table data from SQLite database
Future<List<List<String>>> getSqliteTableData(
        {required String dbPath,
        required String table,
        int? limit,
        int? offset}) =>
    RustLib.instance.api.crateApiSqliteGetSqliteTableData(
        dbPath: dbPath, table: table, limit: limit, offset: offset);
