// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `logs_dir`

/// Spawn a new terminal session for a project
Future<String> spawnTerminalSession({required String projectId, String? cwd}) =>
    RustLib.instance.api
        .crateApiTerminalSpawnTerminalSession(projectId: projectId, cwd: cwd);

/// Write data to a terminal session
Future<void> writeToTerminalSession(
        {required String sessionId, required String data}) =>
    RustLib.instance.api.crateApiTerminalWriteToTerminalSession(
        sessionId: sessionId, data: data);

/// Kill a terminal session
Future<void> killTerminalSession({required String sessionId}) =>
    RustLib.instance.api
        .crateApiTerminalKillTerminalSession(sessionId: sessionId);

/// Resize a terminal session
Future<void> resizeTerminalSession(
        {required String sessionId, required int cols, required int rows}) =>
    RustLib.instance.api.crateApiTerminalResizeTerminalSession(
        sessionId: sessionId, cols: cols, rows: rows);
