// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Open a new window (via platform shell)
Future<void> openNewWindow() =>
    RustLib.instance.api.crateApiWindowsOpenNewWindow();

/// Open the Ping utility window
Future<void> openPingWindow() =>
    RustLib.instance.api.crateApiWindowsOpenPingWindow();

/// Open the Admin settings window
Future<void> openAdminWindow() =>
    RustLib.instance.api.crateApiWindowsOpenAdminWindow();

/// Open the Zen Browser window
Future<void> openBrowserWindow() =>
    RustLib.instance.api.crateApiWindowsOpenBrowserWindow();

/// Hide or close the current window
Future<void> hideOrCloseWindow() =>
    RustLib.instance.api.crateApiWindowsHideOrCloseWindow();
