// flutter_rust_bridge (FRB) integration layer
// Mirrors all Tauri IPC commands from tauri_app/src-tauri/src/main.rs
// These will be generated by FRB from the Rust side; for now we define the interface.

import '../models/project.dart';

/// Abstract interface that mirrors all Tauri IPC commands.
/// When FRB is fully wired, these will call into generated Dart bindings.
/// For now, this provides the contract so UI components can be built in parallel.
abstract class RustBridgeService {
  // ── Process Management ──
  Future<void> startProjectProcess(String projectId);
  Future<void> stopProjectProcess(String projectId);
  Future<List<Project>> getProjects();
  Future<List<LogLine>> getProjectLogs(String projectId);
  Future<ProcessState> getProjectState(String projectId);
  Future<void> registerProject(Map<String, dynamic> config);
  Future<void> deregisterProject(String projectId);

  // ── Terminal ──
  Future<String> spawnTerminalSession(String projectId, String? cwd);
  Future<void> syncTerminalInputBuf(String sessionId, String input);
  Future<void> writeToTerminalSession(String sessionId, String data);
  Future<void> killTerminalSession(String sessionId);
  Future<bool> checkTerminalSession(String sessionId);
  Future<void> resizeTerminalSession(String sessionId, int cols, int rows);

  // ── Files ──
  Future<List<Map<String, dynamic>>> getProjectFiles(String cwd);
  Future<List<Map<String, dynamic>>> getAllFilesAndFolders(String cwd);
  Future<List<int>> readFileContent(String path);
  Future<void> writeFileContent(String path, String content);
  Future<void> createFile(String file);
  Future<void> createFolder(String folder);
  Future<Map<String, dynamic>> getDirectoryContents(String path);
  Future<String?> openFileDialog();
  Future<String?> openFolderDialog();
  Future<String?> saveFileDialog(String defaultName);

  // ── Network ──
  Future<bool> checkPortStatus(int port);
  Future<void> forceKillProcess(int pid);
  Future<Map<String, dynamic>> sendHttpRequest(Map<String, dynamic> request);
  Future<Map<String, dynamic>> dnsLookup(String host);
  Future<Map<String, dynamic>> pingHost(String host);
  Future<Map<String, dynamic>> sslCertificateInfo(String url);

  // ── Settings ──
  Future<AppSettings> getSettings();
  Future<void> saveSettings(AppSettings settings);
  Future<void> resetSettings();

  // ── SQLite ──
  Future<List<String>> getSqliteTables(String dbPath);
  Future<List<Map<String, dynamic>>> getSqliteTableData(String dbPath, String table, {int? limit, int? offset});
  Future<void> updateSqliteCell(String dbPath, String table, String column, dynamic value, String pkColumn, dynamic pkValue);
  Future<void> insertSqliteRow(String dbPath, String table, Map<String, dynamic> data);
  Future<void> deleteSqliteRow(String dbPath, String table, String pkColumn, dynamic pkValue);
  Future<void> addSqliteColumn(String dbPath, String table, String columnName, String columnType);

  // ── Agent ──
  Future<String> agentSendMessage(Map<String, dynamic> msg);
  Future<void> agentApproveTool(bool approve, String? reason);
  Future<void> agentResetSession();
  Future<void> agentCancel();
  Future<Map<String, dynamic>?> agentStatus();
  Future<List<Map<String, dynamic>>> agentGetHistory();
  Future<Map<String, dynamic>> loadAgentSession(String sessionId);
  Future<void> saveAgentSession(Map<String, dynamic> session);
  Future<void> agentDeleteSession(String sessionId);

  // ── Git ──
  Future<Map<String, dynamic>> gitGetStatus(String cwd);
  Future<void> gitStageFile(String cwd, String file);
  Future<void> gitStageAll(String cwd);
  Future<void> gitUnstageFile(String cwd, String file);
  Future<void> gitUnstageAll(String cwd);
  Future<void> gitDiscardFile(String cwd, String file);
  Future<void> gitCommit(String cwd, String message);
  Future<void> gitPush(String cwd);
  Future<void> gitPull(String cwd);
  Future<List<Map<String, dynamic>>> gitGetLog(String cwd, {int limit = 20});

  // ── Sandbox ──
  Future<List<Map<String, dynamic>>> loadSandboxConfigs();
  Future<void> saveSandboxConfig(Map<String, dynamic> config);
  Future<void> saveAllSandboxConfigs(List<Map<String, dynamic>> configs);
  Future<void> deleteSandboxConfig(String id);

  // ── Environment Simulation ──
  Future<List<Map<String, dynamic>>> loadEnvSimulationConfigs();
  Future<void> saveEnvSimulationConfig(Map<String, dynamic> config);

  // ── Cloudflare ──
  Future<Map<String, dynamic>> loadCloudflareConfig();
  Future<void> saveCloudflareConfig(Map<String, dynamic> config);

  // ── Language Runtimes ──
  Future<List<Map<String, dynamic>>> getLanguageRuntimes();
  Future<void> saveLanguageRuntime(Map<String, dynamic> runtime);
  Future<void> deleteLanguageRuntime(String name);

  // ── Code RAG ──
  Future<List<String>> codeRagSupportedLanguages();
  Future<Map<String, String>> codeRagExtensionMap();
  Future<Map<String, dynamic>> codeRagHealth();
  Future<List<Map<String, dynamic>>> codeRagQuery(String query, {List<String>? files});
  Future<Map<String, dynamic>> codeRagStats();

  // ── Windows & Dialogs ──
  Future<void> openNewWindow();
  Future<void> openPingWindow();
  Future<void> openAdminWindow();
  Future<void> openBrowserWindow();
  Future<void> hideOrCloseWindow();

  // ── Alouette Open ──
  Future<void> toggleAlouetteOpen(bool enabled);
  Future<bool> isAlouetteOpenActive();
}

/// Placeholder implementation that will be replaced by real FRB-generated code.
class PlaceholderRustBridge implements RustBridgeService {
  @override
  Future<void> startProjectProcess(String projectId) async =>
      print('FRB: startProjectProcess($projectId)');

  @override
  Future<void> stopProjectProcess(String projectId) async =>
      print('FRB: stopProjectProcess($projectId)');

  @override
  Future<List<Project>> getProjects() async => [];

  @override
  Future<List<LogLine>> getProjectLogs(String projectId) async => [];

  @override
  Future<ProcessState> getProjectState(String projectId) async =>
      ProcessState(type: ProcessStateType.stopped);

  @override
  Future<void> registerProject(Map<String, dynamic> config) async =>
      print('FRB: registerProject($config)');

  @override
  Future<void> deregisterProject(String projectId) async =>
      print('FRB: deregisterProject($projectId)');

  @override
  Future<String> spawnTerminalSession(String projectId, String? cwd) async =>
      'dummy-session-id';

  @override
  Future<void> syncTerminalInputBuf(String sessionId, String input) async {}

  @override
  Future<void> writeToTerminalSession(String sessionId, String data) async {}

  @override
  Future<void> killTerminalSession(String sessionId) async {}

  @override
  Future<bool> checkTerminalSession(String sessionId) async => false;

  @override
  Future<void> resizeTerminalSession(String sessionId, int cols, int rows) async {}

  @override
  Future<List<Map<String, dynamic>>> getProjectFiles(String cwd) async => [];

  @override
  Future<List<Map<String, dynamic>>> getAllFilesAndFolders(String cwd) async => [];

  @override
  Future<List<int>> readFileContent(String path) async => [];

  @override
  Future<void> writeFileContent(String path, String content) async {}

  @override
  Future<void> createFile(String file) async {}

  @override
  Future<void> createFolder(String folder) async {}

  @override
  Future<Map<String, dynamic>> getDirectoryContents(String path) async => {};

  @override
  Future<String?> openFileDialog() async => null;

  @override
  Future<String?> openFolderDialog() async => null;

  @override
  Future<String?> saveFileDialog(String defaultName) async => null;

  @override
  Future<bool> checkPortStatus(int port) async => false;

  @override
  Future<void> forceKillProcess(int pid) async {}

  @override
  Future<Map<String, dynamic>> sendHttpRequest(Map<String, dynamic> request) async => {};

  @override
  Future<Map<String, dynamic>> dnsLookup(String host) async => {};

  @override
  Future<Map<String, dynamic>> pingHost(String host) async => {};

  @override
  Future<Map<String, dynamic>> sslCertificateInfo(String url) async => {};

  @override
  Future<AppSettings> getSettings() async => AppSettings();

  @override
  Future<void> saveSettings(AppSettings settings) async {}

  @override
  Future<void> resetSettings() async {}

  @override
  Future<List<String>> getSqliteTables(String dbPath) async => [];

  @override
  Future<List<Map<String, dynamic>>> getSqliteTableData(String dbPath, String table, {int? limit, int? offset}) async => [];

  @override
  Future<void> updateSqliteCell(String dbPath, String table, String column, dynamic value, String pkColumn, dynamic pkValue) async {}

  @override
  Future<void> insertSqliteRow(String dbPath, String table, Map<String, dynamic> data) async {}

  @override
  Future<void> deleteSqliteRow(String dbPath, String table, String pkColumn, dynamic pkValue) async {}

  @override
  Future<void> addSqliteColumn(String dbPath, String table, String columnName, String columnType) async {}

  @override
  Future<String> agentSendMessage(Map<String, dynamic> msg) async => '';

  @override
  Future<void> agentApproveTool(bool approve, String? reason) async {}

  @override
  Future<void> agentResetSession() async {}

  @override
  Future<void> agentCancel() async {}

  @override
  Future<Map<String, dynamic>?> agentStatus() async => null;

  @override
  Future<List<Map<String, dynamic>>> agentGetHistory() async => [];

  @override
  Future<Map<String, dynamic>> loadAgentSession(String sessionId) async => {};

  @override
  Future<void> saveAgentSession(Map<String, dynamic> session) async {}

  @override
  Future<void> agentDeleteSession(String sessionId) async {}

  @override
  Future<Map<String, dynamic>> gitGetStatus(String cwd) async => {};

  @override
  Future<void> gitStageFile(String cwd, String file) async {}

  @override
  Future<void> gitStageAll(String cwd) async {}

  @override
  Future<void> gitUnstageFile(String cwd, String file) async {}

  @override
  Future<void> gitUnstageAll(String cwd) async {}

  @override
  Future<void> gitDiscardFile(String cwd, String file) async {}

  @override
  Future<void> gitCommit(String cwd, String message) async {}

  @override
  Future<void> gitPush(String cwd) async {}

  @override
  Future<void> gitPull(String cwd) async {}

  @override
  Future<List<Map<String, dynamic>>> gitGetLog(String cwd, {int limit = 20}) async => [];

  @override
  Future<List<Map<String, dynamic>>> loadSandboxConfigs() async => [];

  @override
  Future<void> saveSandboxConfig(Map<String, dynamic> config) async {}

  @override
  Future<void> saveAllSandboxConfigs(List<Map<String, dynamic>> configs) async {}

  @override
  Future<void> deleteSandboxConfig(String id) async {}

  @override
  Future<List<Map<String, dynamic>>> loadEnvSimulationConfigs() async => [];

  @override
  Future<void> saveEnvSimulationConfig(Map<String, dynamic> config) async {}

  @override
  Future<Map<String, dynamic>> loadCloudflareConfig() async => {};

  @override
  Future<void> saveCloudflareConfig(Map<String, dynamic> config) async {}

  @override
  Future<List<Map<String, dynamic>>> getLanguageRuntimes() async => [];

  @override
  Future<void> saveLanguageRuntime(Map<String, dynamic> runtime) async {}

  @override
  Future<void> deleteLanguageRuntime(String name) async {}

  @override
  Future<List<String>> codeRagSupportedLanguages() async => [];

  @override
  Future<Map<String, String>> codeRagExtensionMap() async => {};

  @override
  Future<Map<String, dynamic>> codeRagHealth() async => {};

  @override
  Future<List<Map<String, dynamic>>> codeRagQuery(String query, {List<String>? files}) async => [];

  @override
  Future<Map<String, dynamic>> codeRagStats() async => {};

  @override
  Future<void> openNewWindow() async {}

  @override
  Future<void> openPingWindow() async {}

  @override
  Future<void> openAdminWindow() async {}

  @override
  Future<void> openBrowserWindow() async {}

  @override
  Future<void> hideOrCloseWindow() async {}

  @override
  Future<void> toggleAlouetteOpen(bool enabled) async {}

  @override
  Future<bool> isAlouetteOpenActive() async => false;
}
