// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent.dart';
import 'api/alouette_open.dart';
import 'api/cloudflare.dart';
import 'api/code_rag.dart';
import 'api/config.dart';
import 'api/files.dart';
import 'api/git.dart';
import 'api/language.dart';
import 'api/local_chat.dart';
import 'api/network.dart';
import 'api/process.dart';
import 'api/sandbox.dart';
import 'api/settings.dart';
import 'api/sqlite.dart';
import 'api/terminal.dart';
import 'api/windows.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1804720469;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'alouette_bridge',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiAgentAgentApproveTool(
      {required bool approve, String? reason});

  Future<void> crateApiAgentAgentCancel();

  Future<void> crateApiAgentAgentDeleteSession({required String sessionId});

  Future<List<String>> crateApiAgentAgentGetHistory();

  Future<void> crateApiAgentAgentResetSession();

  Future<String> crateApiAgentAgentSendMessage({required String msg});

  Future<String> crateApiAgentAgentStatus();

  Future<bool> crateApiNetworkCheckPortStatus({required int port});

  Future<Map<String, String>> crateApiCodeRagCodeRagExtensionMap();

  Future<String> crateApiCodeRagCodeRagHealth();

  Future<List<String>> crateApiCodeRagCodeRagSupportedLanguages();

  Future<void> crateApiFilesCreateFile({required String path});

  Future<void> crateApiFilesCreateFolder({required String path});

  Future<void> crateApiProcessDeregisterProject({required String projectId});

  Future<List<String>> crateApiNetworkDnsLookup({required String host});

  Future<void> crateApiProcessForceKillProcess({required int pid});

  Future<String> crateApiAgentGetCustomAiConfig();

  Future<List<FileEntry>> crateApiFilesGetDirectoryContents(
      {required String path});

  Future<List<RuntimeInfo>> crateApiLanguageGetLanguageRuntimes();

  Future<List<LogLine>> crateApiProcessGetProjectLogs(
      {required String projectId});

  Future<List<ProjectInfo>> crateApiProcessGetProjects();

  Future<String> crateApiConfigGetProjectsConfigYaml();

  Future<String> crateApiSettingsGetSettings();

  Future<List<List<String>>> crateApiSqliteGetSqliteTableData(
      {required String dbPath, required String table, int? limit, int? offset});

  Future<List<String>> crateApiSqliteGetSqliteTables({required String dbPath});

  Future<void> crateApiGitGitCommit(
      {required String cwd, required String message});

  Future<List<GitCommit>> crateApiGitGitGetLog(
      {required String cwd, int? limit});

  Future<String> crateApiGitGitGetStatus({required String cwd});

  Future<void> crateApiGitGitPull({required String cwd});

  Future<void> crateApiGitGitPush({required String cwd});

  Future<void> crateApiGitGitStageAll({required String cwd});

  Future<void> crateApiGitGitStageFile(
      {required String cwd, required String file});

  Future<String> crateApiProcessGreet({required String name});

  Future<void> crateApiWindowsHideOrCloseWindow();

  Future<bool> crateApiAlouetteOpenIsAlouetteOpenActive();

  Future<void> crateApiTerminalKillTerminalSession({required String sessionId});

  Future<List<FileEntry>> crateApiFilesListDirectory({required String path});

  Future<String> crateApiAgentLoadAgentSession({required String sessionId});

  Future<String> crateApiCloudflareLoadCloudflareConfig();

  Future<List<String>> crateApiAgentLoadHistoryPage(
      {required int page, required int pageSize});

  Future<List<String>> crateApiSandboxLoadSandboxConfigs();

  Future<String> crateApiLocalChatLocalChatSend({required String message});

  Future<void> crateApiLocalChatLocalChatStop();

  Future<void> crateApiWindowsOpenAdminWindow();

  Future<void> crateApiWindowsOpenBrowserWindow();

  Future<void> crateApiWindowsOpenNewWindow();

  Future<void> crateApiWindowsOpenPingWindow();

  Future<PingResult> crateApiNetworkPingHost({required String host});

  Future<String> crateApiFilesReadFileContent({required String path});

  Future<String> crateApiProcessRegisterProject(
      {required String name,
      required String command,
      required List<String> args,
      String? cwd,
      required bool autoRestart,
      int? port});

  Future<void> crateApiSettingsResetSettings();

  Future<void> crateApiTerminalResizeTerminalSession(
      {required String sessionId, required int cols, required int rows});

  Future<void> crateApiAgentSaveAgentSession(
      {required String sessionId, required String data});

  Future<void> crateApiCloudflareSaveCloudflareConfig({required String yaml});

  Future<void> crateApiAgentSaveCustomAiConfig({required String config});

  Future<void> crateApiSandboxSaveSandboxConfig({required String json});

  Future<void> crateApiSettingsSaveSettings({required String content});

  Future<HttpResponse> crateApiNetworkSendHttpRequest(
      {required String method,
      required String url,
      List<HeaderPair>? headers,
      String? body});

  Future<String> crateApiTerminalSpawnTerminalSession(
      {required String projectId, String? cwd});

  Future<String> crateApiNetworkSslCertificateInfo({required String url});

  Future<void> crateApiProcessStartProjectProcess({required String projectId});

  Future<void> crateApiProcessStopProjectProcess({required String projectId});

  Future<void> crateApiAgentSwitchAgentProject({required String projectId});

  Future<void> crateApiAlouetteOpenToggleAlouetteOpen({required bool enabled});

  Future<void> crateApiFilesWriteFileContent(
      {required String path, required String content});

  Future<void> crateApiTerminalWriteToTerminalSession(
      {required String sessionId, required String data});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiAgentAgentApproveTool(
      {required bool approve, String? reason}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(approve, serializer);
        sse_encode_opt_String(reason, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentApproveToolConstMeta,
      argValues: [approve, reason],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentApproveToolConstMeta =>
      const TaskConstMeta(
        debugName: "agent_approve_tool",
        argNames: ["approve", "reason"],
      );

  @override
  Future<void> crateApiAgentAgentCancel() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentCancelConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentCancelConstMeta => const TaskConstMeta(
        debugName: "agent_cancel",
        argNames: [],
      );

  @override
  Future<void> crateApiAgentAgentDeleteSession({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentDeleteSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentDeleteSessionConstMeta =>
      const TaskConstMeta(
        debugName: "agent_delete_session",
        argNames: ["sessionId"],
      );

  @override
  Future<List<String>> crateApiAgentAgentGetHistory() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentGetHistoryConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentGetHistoryConstMeta =>
      const TaskConstMeta(
        debugName: "agent_get_history",
        argNames: [],
      );

  @override
  Future<void> crateApiAgentAgentResetSession() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentResetSessionConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentResetSessionConstMeta =>
      const TaskConstMeta(
        debugName: "agent_reset_session",
        argNames: [],
      );

  @override
  Future<String> crateApiAgentAgentSendMessage({required String msg}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(msg, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentSendMessageConstMeta,
      argValues: [msg],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentSendMessageConstMeta =>
      const TaskConstMeta(
        debugName: "agent_send_message",
        argNames: ["msg"],
      );

  @override
  Future<String> crateApiAgentAgentStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentAgentStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentAgentStatusConstMeta => const TaskConstMeta(
        debugName: "agent_status",
        argNames: [],
      );

  @override
  Future<bool> crateApiNetworkCheckPortStatus({required int port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(port, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNetworkCheckPortStatusConstMeta,
      argValues: [port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetworkCheckPortStatusConstMeta =>
      const TaskConstMeta(
        debugName: "check_port_status",
        argNames: ["port"],
      );

  @override
  Future<Map<String, String>> crateApiCodeRagCodeRagExtensionMap() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_Map_String_String_None,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCodeRagCodeRagExtensionMapConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCodeRagCodeRagExtensionMapConstMeta =>
      const TaskConstMeta(
        debugName: "code_rag_extension_map",
        argNames: [],
      );

  @override
  Future<String> crateApiCodeRagCodeRagHealth() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCodeRagCodeRagHealthConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCodeRagCodeRagHealthConstMeta =>
      const TaskConstMeta(
        debugName: "code_rag_health",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiCodeRagCodeRagSupportedLanguages() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiCodeRagCodeRagSupportedLanguagesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCodeRagCodeRagSupportedLanguagesConstMeta =>
      const TaskConstMeta(
        debugName: "code_rag_supported_languages",
        argNames: [],
      );

  @override
  Future<void> crateApiFilesCreateFile({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesCreateFileConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesCreateFileConstMeta => const TaskConstMeta(
        debugName: "create_file",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiFilesCreateFolder({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesCreateFolderConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesCreateFolderConstMeta => const TaskConstMeta(
        debugName: "create_folder",
        argNames: ["path"],
      );

  @override
  Future<void> crateApiProcessDeregisterProject({required String projectId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessDeregisterProjectConstMeta,
      argValues: [projectId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessDeregisterProjectConstMeta =>
      const TaskConstMeta(
        debugName: "deregister_project",
        argNames: ["projectId"],
      );

  @override
  Future<List<String>> crateApiNetworkDnsLookup({required String host}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNetworkDnsLookupConstMeta,
      argValues: [host],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetworkDnsLookupConstMeta => const TaskConstMeta(
        debugName: "dns_lookup",
        argNames: ["host"],
      );

  @override
  Future<void> crateApiProcessForceKillProcess({required int pid}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(pid, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessForceKillProcessConstMeta,
      argValues: [pid],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessForceKillProcessConstMeta =>
      const TaskConstMeta(
        debugName: "force_kill_process",
        argNames: ["pid"],
      );

  @override
  Future<String> crateApiAgentGetCustomAiConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentGetCustomAiConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentGetCustomAiConfigConstMeta =>
      const TaskConstMeta(
        debugName: "get_custom_ai_config",
        argNames: [],
      );

  @override
  Future<List<FileEntry>> crateApiFilesGetDirectoryContents(
      {required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 18, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_file_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesGetDirectoryContentsConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesGetDirectoryContentsConstMeta =>
      const TaskConstMeta(
        debugName: "get_directory_contents",
        argNames: ["path"],
      );

  @override
  Future<List<RuntimeInfo>> crateApiLanguageGetLanguageRuntimes() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 19, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_runtime_info,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiLanguageGetLanguageRuntimesConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLanguageGetLanguageRuntimesConstMeta =>
      const TaskConstMeta(
        debugName: "get_language_runtimes",
        argNames: [],
      );

  @override
  Future<List<LogLine>> crateApiProcessGetProjectLogs(
      {required String projectId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 20, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_log_line,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessGetProjectLogsConstMeta,
      argValues: [projectId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessGetProjectLogsConstMeta =>
      const TaskConstMeta(
        debugName: "get_project_logs",
        argNames: ["projectId"],
      );

  @override
  Future<List<ProjectInfo>> crateApiProcessGetProjects() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 21, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_project_info,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessGetProjectsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessGetProjectsConstMeta => const TaskConstMeta(
        debugName: "get_projects",
        argNames: [],
      );

  @override
  Future<String> crateApiConfigGetProjectsConfigYaml() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 22, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiConfigGetProjectsConfigYamlConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiConfigGetProjectsConfigYamlConstMeta =>
      const TaskConstMeta(
        debugName: "get_projects_config_yaml",
        argNames: [],
      );

  @override
  Future<String> crateApiSettingsGetSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 23, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSettingsGetSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsGetSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "get_settings",
        argNames: [],
      );

  @override
  Future<List<List<String>>> crateApiSqliteGetSqliteTableData(
      {required String dbPath,
      required String table,
      int? limit,
      int? offset}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        sse_encode_String(table, serializer);
        sse_encode_opt_box_autoadd_i_32(limit, serializer);
        sse_encode_opt_box_autoadd_i_32(offset, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 24, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSqliteGetSqliteTableDataConstMeta,
      argValues: [dbPath, table, limit, offset],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSqliteGetSqliteTableDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_sqlite_table_data",
        argNames: ["dbPath", "table", "limit", "offset"],
      );

  @override
  Future<List<String>> crateApiSqliteGetSqliteTables({required String dbPath}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dbPath, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 25, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSqliteGetSqliteTablesConstMeta,
      argValues: [dbPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSqliteGetSqliteTablesConstMeta =>
      const TaskConstMeta(
        debugName: "get_sqlite_tables",
        argNames: ["dbPath"],
      );

  @override
  Future<void> crateApiGitGitCommit(
      {required String cwd, required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 26, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitCommitConstMeta,
      argValues: [cwd, message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitCommitConstMeta => const TaskConstMeta(
        debugName: "git_commit",
        argNames: ["cwd", "message"],
      );

  @override
  Future<List<GitCommit>> crateApiGitGitGetLog(
      {required String cwd, int? limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        sse_encode_opt_box_autoadd_i_32(limit, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 27, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_git_commit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitGetLogConstMeta,
      argValues: [cwd, limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitGetLogConstMeta => const TaskConstMeta(
        debugName: "git_get_log",
        argNames: ["cwd", "limit"],
      );

  @override
  Future<String> crateApiGitGitGetStatus({required String cwd}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 28, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitGetStatusConstMeta,
      argValues: [cwd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitGetStatusConstMeta => const TaskConstMeta(
        debugName: "git_get_status",
        argNames: ["cwd"],
      );

  @override
  Future<void> crateApiGitGitPull({required String cwd}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 29, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitPullConstMeta,
      argValues: [cwd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitPullConstMeta => const TaskConstMeta(
        debugName: "git_pull",
        argNames: ["cwd"],
      );

  @override
  Future<void> crateApiGitGitPush({required String cwd}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 30, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitPushConstMeta,
      argValues: [cwd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitPushConstMeta => const TaskConstMeta(
        debugName: "git_push",
        argNames: ["cwd"],
      );

  @override
  Future<void> crateApiGitGitStageAll({required String cwd}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 31, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitStageAllConstMeta,
      argValues: [cwd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitStageAllConstMeta => const TaskConstMeta(
        debugName: "git_stage_all",
        argNames: ["cwd"],
      );

  @override
  Future<void> crateApiGitGitStageFile(
      {required String cwd, required String file}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cwd, serializer);
        sse_encode_String(file, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 32, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiGitGitStageFileConstMeta,
      argValues: [cwd, file],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiGitGitStageFileConstMeta => const TaskConstMeta(
        debugName: "git_stage_file",
        argNames: ["cwd", "file"],
      );

  @override
  Future<String> crateApiProcessGreet({required String name}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 33, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiProcessGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiWindowsHideOrCloseWindow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 34, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsHideOrCloseWindowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsHideOrCloseWindowConstMeta =>
      const TaskConstMeta(
        debugName: "hide_or_close_window",
        argNames: [],
      );

  @override
  Future<bool> crateApiAlouetteOpenIsAlouetteOpenActive() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 35, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAlouetteOpenIsAlouetteOpenActiveConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAlouetteOpenIsAlouetteOpenActiveConstMeta =>
      const TaskConstMeta(
        debugName: "is_alouette_open_active",
        argNames: [],
      );

  @override
  Future<void> crateApiTerminalKillTerminalSession(
      {required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 36, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTerminalKillTerminalSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTerminalKillTerminalSessionConstMeta =>
      const TaskConstMeta(
        debugName: "kill_terminal_session",
        argNames: ["sessionId"],
      );

  @override
  Future<List<FileEntry>> crateApiFilesListDirectory({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 37, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_file_entry,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesListDirectoryConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesListDirectoryConstMeta => const TaskConstMeta(
        debugName: "list_directory",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiAgentLoadAgentSession({required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 38, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentLoadAgentSessionConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentLoadAgentSessionConstMeta =>
      const TaskConstMeta(
        debugName: "load_agent_session",
        argNames: ["sessionId"],
      );

  @override
  Future<String> crateApiCloudflareLoadCloudflareConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 39, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCloudflareLoadCloudflareConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCloudflareLoadCloudflareConfigConstMeta =>
      const TaskConstMeta(
        debugName: "load_cloudflare_config",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiAgentLoadHistoryPage(
      {required int page, required int pageSize}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_i_32(page, serializer);
        sse_encode_i_32(pageSize, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 40, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentLoadHistoryPageConstMeta,
      argValues: [page, pageSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentLoadHistoryPageConstMeta =>
      const TaskConstMeta(
        debugName: "load_history_page",
        argNames: ["page", "pageSize"],
      );

  @override
  Future<List<String>> crateApiSandboxLoadSandboxConfigs() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 41, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSandboxLoadSandboxConfigsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSandboxLoadSandboxConfigsConstMeta =>
      const TaskConstMeta(
        debugName: "load_sandbox_configs",
        argNames: [],
      );

  @override
  Future<String> crateApiLocalChatLocalChatSend({required String message}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(message, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 42, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLocalChatLocalChatSendConstMeta,
      argValues: [message],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLocalChatLocalChatSendConstMeta =>
      const TaskConstMeta(
        debugName: "local_chat_send",
        argNames: ["message"],
      );

  @override
  Future<void> crateApiLocalChatLocalChatStop() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 43, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiLocalChatLocalChatStopConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiLocalChatLocalChatStopConstMeta =>
      const TaskConstMeta(
        debugName: "local_chat_stop",
        argNames: [],
      );

  @override
  Future<void> crateApiWindowsOpenAdminWindow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 44, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsOpenAdminWindowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsOpenAdminWindowConstMeta =>
      const TaskConstMeta(
        debugName: "open_admin_window",
        argNames: [],
      );

  @override
  Future<void> crateApiWindowsOpenBrowserWindow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 45, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsOpenBrowserWindowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsOpenBrowserWindowConstMeta =>
      const TaskConstMeta(
        debugName: "open_browser_window",
        argNames: [],
      );

  @override
  Future<void> crateApiWindowsOpenNewWindow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 46, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsOpenNewWindowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsOpenNewWindowConstMeta =>
      const TaskConstMeta(
        debugName: "open_new_window",
        argNames: [],
      );

  @override
  Future<void> crateApiWindowsOpenPingWindow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 47, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiWindowsOpenPingWindowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiWindowsOpenPingWindowConstMeta =>
      const TaskConstMeta(
        debugName: "open_ping_window",
        argNames: [],
      );

  @override
  Future<PingResult> crateApiNetworkPingHost({required String host}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(host, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 48, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ping_result,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNetworkPingHostConstMeta,
      argValues: [host],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetworkPingHostConstMeta => const TaskConstMeta(
        debugName: "ping_host",
        argNames: ["host"],
      );

  @override
  Future<String> crateApiFilesReadFileContent({required String path}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 49, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesReadFileContentConstMeta,
      argValues: [path],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesReadFileContentConstMeta =>
      const TaskConstMeta(
        debugName: "read_file_content",
        argNames: ["path"],
      );

  @override
  Future<String> crateApiProcessRegisterProject(
      {required String name,
      required String command,
      required List<String> args,
      String? cwd,
      required bool autoRestart,
      int? port}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        sse_encode_String(command, serializer);
        sse_encode_list_String(args, serializer);
        sse_encode_opt_String(cwd, serializer);
        sse_encode_bool(autoRestart, serializer);
        sse_encode_opt_box_autoadd_i_32(port, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 50, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessRegisterProjectConstMeta,
      argValues: [name, command, args, cwd, autoRestart, port],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessRegisterProjectConstMeta =>
      const TaskConstMeta(
        debugName: "register_project",
        argNames: ["name", "command", "args", "cwd", "autoRestart", "port"],
      );

  @override
  Future<void> crateApiSettingsResetSettings() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 51, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSettingsResetSettingsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsResetSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "reset_settings",
        argNames: [],
      );

  @override
  Future<void> crateApiTerminalResizeTerminalSession(
      {required String sessionId, required int cols, required int rows}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_i_32(cols, serializer);
        sse_encode_i_32(rows, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 52, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTerminalResizeTerminalSessionConstMeta,
      argValues: [sessionId, cols, rows],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTerminalResizeTerminalSessionConstMeta =>
      const TaskConstMeta(
        debugName: "resize_terminal_session",
        argNames: ["sessionId", "cols", "rows"],
      );

  @override
  Future<void> crateApiAgentSaveAgentSession(
      {required String sessionId, required String data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_String(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 53, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentSaveAgentSessionConstMeta,
      argValues: [sessionId, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentSaveAgentSessionConstMeta =>
      const TaskConstMeta(
        debugName: "save_agent_session",
        argNames: ["sessionId", "data"],
      );

  @override
  Future<void> crateApiCloudflareSaveCloudflareConfig({required String yaml}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(yaml, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 54, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiCloudflareSaveCloudflareConfigConstMeta,
      argValues: [yaml],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiCloudflareSaveCloudflareConfigConstMeta =>
      const TaskConstMeta(
        debugName: "save_cloudflare_config",
        argNames: ["yaml"],
      );

  @override
  Future<void> crateApiAgentSaveCustomAiConfig({required String config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(config, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 55, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentSaveCustomAiConfigConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentSaveCustomAiConfigConstMeta =>
      const TaskConstMeta(
        debugName: "save_custom_ai_config",
        argNames: ["config"],
      );

  @override
  Future<void> crateApiSandboxSaveSandboxConfig({required String json}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(json, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 56, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSandboxSaveSandboxConfigConstMeta,
      argValues: [json],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSandboxSaveSandboxConfigConstMeta =>
      const TaskConstMeta(
        debugName: "save_sandbox_config",
        argNames: ["json"],
      );

  @override
  Future<void> crateApiSettingsSaveSettings({required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 57, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiSettingsSaveSettingsConstMeta,
      argValues: [content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSettingsSaveSettingsConstMeta =>
      const TaskConstMeta(
        debugName: "save_settings",
        argNames: ["content"],
      );

  @override
  Future<HttpResponse> crateApiNetworkSendHttpRequest(
      {required String method,
      required String url,
      List<HeaderPair>? headers,
      String? body}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(method, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_list_header_pair(headers, serializer);
        sse_encode_opt_String(body, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 58, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_http_response,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNetworkSendHttpRequestConstMeta,
      argValues: [method, url, headers, body],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetworkSendHttpRequestConstMeta =>
      const TaskConstMeta(
        debugName: "send_http_request",
        argNames: ["method", "url", "headers", "body"],
      );

  @override
  Future<String> crateApiTerminalSpawnTerminalSession(
      {required String projectId, String? cwd}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        sse_encode_opt_String(cwd, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 59, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTerminalSpawnTerminalSessionConstMeta,
      argValues: [projectId, cwd],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTerminalSpawnTerminalSessionConstMeta =>
      const TaskConstMeta(
        debugName: "spawn_terminal_session",
        argNames: ["projectId", "cwd"],
      );

  @override
  Future<String> crateApiNetworkSslCertificateInfo({required String url}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 60, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiNetworkSslCertificateInfoConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiNetworkSslCertificateInfoConstMeta =>
      const TaskConstMeta(
        debugName: "ssl_certificate_info",
        argNames: ["url"],
      );

  @override
  Future<void> crateApiProcessStartProjectProcess({required String projectId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 61, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessStartProjectProcessConstMeta,
      argValues: [projectId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessStartProjectProcessConstMeta =>
      const TaskConstMeta(
        debugName: "start_project_process",
        argNames: ["projectId"],
      );

  @override
  Future<void> crateApiProcessStopProjectProcess({required String projectId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 62, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiProcessStopProjectProcessConstMeta,
      argValues: [projectId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiProcessStopProjectProcessConstMeta =>
      const TaskConstMeta(
        debugName: "stop_project_process",
        argNames: ["projectId"],
      );

  @override
  Future<void> crateApiAgentSwitchAgentProject({required String projectId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(projectId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 63, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiAgentSwitchAgentProjectConstMeta,
      argValues: [projectId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAgentSwitchAgentProjectConstMeta =>
      const TaskConstMeta(
        debugName: "switch_agent_project",
        argNames: ["projectId"],
      );

  @override
  Future<void> crateApiAlouetteOpenToggleAlouetteOpen({required bool enabled}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_bool(enabled, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 64, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiAlouetteOpenToggleAlouetteOpenConstMeta,
      argValues: [enabled],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiAlouetteOpenToggleAlouetteOpenConstMeta =>
      const TaskConstMeta(
        debugName: "toggle_alouette_open",
        argNames: ["enabled"],
      );

  @override
  Future<void> crateApiFilesWriteFileContent(
      {required String path, required String content}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(path, serializer);
        sse_encode_String(content, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 65, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiFilesWriteFileContentConstMeta,
      argValues: [path, content],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFilesWriteFileContentConstMeta =>
      const TaskConstMeta(
        debugName: "write_file_content",
        argNames: ["path", "content"],
      );

  @override
  Future<void> crateApiTerminalWriteToTerminalSession(
      {required String sessionId, required String data}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        sse_encode_String(data, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 66, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_String,
      ),
      constMeta: kCrateApiTerminalWriteToTerminalSessionConstMeta,
      argValues: [sessionId, data],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTerminalWriteToTerminalSessionConstMeta =>
      const TaskConstMeta(
        debugName: "write_to_terminal_session",
        argNames: ["sessionId", "data"],
      );

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(dco_decode_list_record_string_string(raw)
        .map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  FileEntry dco_decode_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FileEntry(
      name: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      isFolder: dco_decode_bool(arr[2]),
    );
  }

  @protected
  GitCommit dco_decode_git_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GitCommit(
      hash: dco_decode_String(arr[0]),
      author: dco_decode_String(arr[1]),
      email: dco_decode_String(arr[2]),
      timestamp: dco_decode_i_64(arr[3]),
      message: dco_decode_String(arr[4]),
    );
  }

  @protected
  HeaderPair dco_decode_header_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return HeaderPair(
      name: dco_decode_String(arr[0]),
      value: dco_decode_String(arr[1]),
    );
  }

  @protected
  HttpResponse dco_decode_http_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return HttpResponse(
      status: dco_decode_i_32(arr[0]),
      headers: dco_decode_list_header_pair(arr[1]),
      body: dco_decode_String(arr[2]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_file_entry).toList();
  }

  @protected
  List<GitCommit> dco_decode_list_git_commit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_git_commit).toList();
  }

  @protected
  List<HeaderPair> dco_decode_list_header_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_header_pair).toList();
  }

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_String).toList();
  }

  @protected
  List<LogLine> dco_decode_list_log_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_log_line).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectInfo> dco_decode_list_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_info).toList();
  }

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_record_string_string).toList();
  }

  @protected
  List<RuntimeInfo> dco_decode_list_runtime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_runtime_info).toList();
  }

  @protected
  LogLine dco_decode_log_line(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return LogLine(
      text: dco_decode_String(arr[0]),
      stream: dco_decode_String(arr[1]),
      timestamp: dco_decode_i_64(arr[2]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_32(raw);
  }

  @protected
  List<HeaderPair>? dco_decode_opt_list_header_pair(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_header_pair(raw);
  }

  @protected
  PingResult dco_decode_ping_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return PingResult(
      reachable: dco_decode_bool(arr[0]),
      latencyMs: dco_decode_i_64(arr[1]),
    );
  }

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return ProjectInfo(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      command: dco_decode_String(arr[2]),
      args: dco_decode_list_String(arr[3]),
      cwd: dco_decode_opt_String(arr[4]),
      autoRestart: dco_decode_bool(arr[5]),
      port: dco_decode_opt_box_autoadd_i_32(arr[6]),
    );
  }

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_String(arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RuntimeInfo(
      name: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_string(deserializer);
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_32(deserializer));
  }

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_isFolder = sse_decode_bool(deserializer);
    return FileEntry(name: var_name, path: var_path, isFolder: var_isFolder);
  }

  @protected
  GitCommit sse_decode_git_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_hash = sse_decode_String(deserializer);
    var var_author = sse_decode_String(deserializer);
    var var_email = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_message = sse_decode_String(deserializer);
    return GitCommit(
        hash: var_hash,
        author: var_author,
        email: var_email,
        timestamp: var_timestamp,
        message: var_message);
  }

  @protected
  HeaderPair sse_decode_header_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_value = sse_decode_String(deserializer);
    return HeaderPair(name: var_name, value: var_value);
  }

  @protected
  HttpResponse sse_decode_http_response(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_i_32(deserializer);
    var var_headers = sse_decode_list_header_pair(deserializer);
    var var_body = sse_decode_String(deserializer);
    return HttpResponse(
        status: var_status, headers: var_headers, body: var_body);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FileEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_file_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<GitCommit> sse_decode_list_git_commit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GitCommit>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_git_commit(deserializer));
    }
    return ans_;
  }

  @protected
  List<HeaderPair> sse_decode_list_header_pair(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <HeaderPair>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_header_pair(deserializer));
    }
    return ans_;
  }

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <List<String>>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<LogLine> sse_decode_list_log_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LogLine>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_log_line(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectInfo> sse_decode_list_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_info(deserializer));
    }
    return ans_;
  }

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, String)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_string(deserializer));
    }
    return ans_;
  }

  @protected
  List<RuntimeInfo> sse_decode_list_runtime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RuntimeInfo>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_runtime_info(deserializer));
    }
    return ans_;
  }

  @protected
  LogLine sse_decode_log_line(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_stream = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    return LogLine(
        text: var_text, stream: var_stream, timestamp: var_timestamp);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  List<HeaderPair>? sse_decode_opt_list_header_pair(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_header_pair(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PingResult sse_decode_ping_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_reachable = sse_decode_bool(deserializer);
    var var_latencyMs = sse_decode_i_64(deserializer);
    return PingResult(reachable: var_reachable, latencyMs: var_latencyMs);
  }

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_command = sse_decode_String(deserializer);
    var var_args = sse_decode_list_String(deserializer);
    var var_cwd = sse_decode_opt_String(deserializer);
    var var_autoRestart = sse_decode_bool(deserializer);
    var var_port = sse_decode_opt_box_autoadd_i_32(deserializer);
    return ProjectInfo(
        id: var_id,
        name: var_name,
        command: var_command,
        args: var_args,
        cwd: var_cwd,
        autoRestart: var_autoRestart,
        port: var_port);
  }

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    return RuntimeInfo(name: var_name, version: var_version);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_string(
        self.entries.map((e) => (e.key, e.value)).toList(), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self, serializer);
  }

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_bool(self.isFolder, serializer);
  }

  @protected
  void sse_encode_git_commit(GitCommit self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.hash, serializer);
    sse_encode_String(self.author, serializer);
    sse_encode_String(self.email, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_header_pair(HeaderPair self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.value, serializer);
  }

  @protected
  void sse_encode_http_response(HttpResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.status, serializer);
    sse_encode_list_header_pair(self.headers, serializer);
    sse_encode_String(self.body, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_file_entry(
      List<FileEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_file_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_git_commit(
      List<GitCommit> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_git_commit(item, serializer);
    }
  }

  @protected
  void sse_encode_list_header_pair(
      List<HeaderPair> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_header_pair(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_log_line(List<LogLine> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_log_line(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_info(
      List<ProjectInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_info(item, serializer);
    }
  }

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_string(item, serializer);
    }
  }

  @protected
  void sse_encode_list_runtime_info(
      List<RuntimeInfo> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_runtime_info(item, serializer);
    }
  }

  @protected
  void sse_encode_log_line(LogLine self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_String(self.stream, serializer);
    sse_encode_i_64(self.timestamp, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_32(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_header_pair(
      List<HeaderPair>? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_header_pair(self, serializer);
    }
  }

  @protected
  void sse_encode_ping_result(PingResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.reachable, serializer);
    sse_encode_i_64(self.latencyMs, serializer);
  }

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.command, serializer);
    sse_encode_list_String(self.args, serializer);
    sse_encode_opt_String(self.cwd, serializer);
    sse_encode_bool(self.autoRestart, serializer);
    sse_encode_opt_box_autoadd_i_32(self.port, serializer);
  }

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.version, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
