// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/agent.dart';
import 'api/alouette_open.dart';
import 'api/cloudflare.dart';
import 'api/code_rag.dart';
import 'api/config.dart';
import 'api/files.dart';
import 'api/git.dart';
import 'api/language.dart';
import 'api/local_chat.dart';
import 'api/network.dart';
import 'api/process.dart';
import 'api/sandbox.dart';
import 'api/settings.dart';
import 'api/sqlite.dart';
import 'api/terminal.dart';
import 'api/windows.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, String> dco_decode_Map_String_String_None(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  int dco_decode_box_autoadd_i_32(dynamic raw);

  @protected
  FileEntry dco_decode_file_entry(dynamic raw);

  @protected
  GitCommit dco_decode_git_commit(dynamic raw);

  @protected
  HeaderPair dco_decode_header_pair(dynamic raw);

  @protected
  HttpResponse dco_decode_http_response(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FileEntry> dco_decode_list_file_entry(dynamic raw);

  @protected
  List<GitCommit> dco_decode_list_git_commit(dynamic raw);

  @protected
  List<HeaderPair> dco_decode_list_header_pair(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  List<LogLine> dco_decode_list_log_line(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectInfo> dco_decode_list_project_info(dynamic raw);

  @protected
  List<(String, String)> dco_decode_list_record_string_string(dynamic raw);

  @protected
  List<RuntimeInfo> dco_decode_list_runtime_info(dynamic raw);

  @protected
  LogLine dco_decode_log_line(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_i_32(dynamic raw);

  @protected
  List<HeaderPair>? dco_decode_opt_list_header_pair(dynamic raw);

  @protected
  PingResult dco_decode_ping_result(dynamic raw);

  @protected
  ProjectInfo dco_decode_project_info(dynamic raw);

  @protected
  (String, String) dco_decode_record_string_string(dynamic raw);

  @protected
  RuntimeInfo dco_decode_runtime_info(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  Map<String, String> sse_decode_Map_String_String_None(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  FileEntry sse_decode_file_entry(SseDeserializer deserializer);

  @protected
  GitCommit sse_decode_git_commit(SseDeserializer deserializer);

  @protected
  HeaderPair sse_decode_header_pair(SseDeserializer deserializer);

  @protected
  HttpResponse sse_decode_http_response(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FileEntry> sse_decode_list_file_entry(SseDeserializer deserializer);

  @protected
  List<GitCommit> sse_decode_list_git_commit(SseDeserializer deserializer);

  @protected
  List<HeaderPair> sse_decode_list_header_pair(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  List<LogLine> sse_decode_list_log_line(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectInfo> sse_decode_list_project_info(SseDeserializer deserializer);

  @protected
  List<(String, String)> sse_decode_list_record_string_string(
      SseDeserializer deserializer);

  @protected
  List<RuntimeInfo> sse_decode_list_runtime_info(SseDeserializer deserializer);

  @protected
  LogLine sse_decode_log_line(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_i_32(SseDeserializer deserializer);

  @protected
  List<HeaderPair>? sse_decode_opt_list_header_pair(
      SseDeserializer deserializer);

  @protected
  PingResult sse_decode_ping_result(SseDeserializer deserializer);

  @protected
  ProjectInfo sse_decode_project_info(SseDeserializer deserializer);

  @protected
  (String, String) sse_decode_record_string_string(
      SseDeserializer deserializer);

  @protected
  RuntimeInfo sse_decode_runtime_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_String_None(
      Map<String, String> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_file_entry(FileEntry self, SseSerializer serializer);

  @protected
  void sse_encode_git_commit(GitCommit self, SseSerializer serializer);

  @protected
  void sse_encode_header_pair(HeaderPair self, SseSerializer serializer);

  @protected
  void sse_encode_http_response(HttpResponse self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_file_entry(
      List<FileEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_git_commit(
      List<GitCommit> self, SseSerializer serializer);

  @protected
  void sse_encode_list_header_pair(
      List<HeaderPair> self, SseSerializer serializer);

  @protected
  void sse_encode_list_list_String(
      List<List<String>> self, SseSerializer serializer);

  @protected
  void sse_encode_list_log_line(List<LogLine> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_project_info(
      List<ProjectInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_record_string_string(
      List<(String, String)> self, SseSerializer serializer);

  @protected
  void sse_encode_list_runtime_info(
      List<RuntimeInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_log_line(LogLine self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_header_pair(
      List<HeaderPair>? self, SseSerializer serializer);

  @protected
  void sse_encode_ping_result(PingResult self, SseSerializer serializer);

  @protected
  void sse_encode_project_info(ProjectInfo self, SseSerializer serializer);

  @protected
  void sse_encode_record_string_string(
      (String, String) self, SseSerializer serializer);

  @protected
  void sse_encode_runtime_info(RuntimeInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
